config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  devise_for :staff_members

  unauthenticated do
    root to: 'pages#main'
  end

  namespace :admin do
    authenticate :staff_member do
      resources :cvs do
        resources :feedbacks
      end
      resources :feedbacks
      resources :jobs
      get '/stats', to: 'pages#stats'
      root 'jobs#index', as: :authenticated_admin_root
    end
  end

  authenticate :user do
    resources :jobs, only: [:index, :show] do
      resources :cvs
    end
    resources :cvs do
      resources :feedbacks, only: [:show] do
        post :accept, :reject
      end
      post :ready
    end
    get '/contact', to: 'pages#contact'
    root 'jobs#index', as: :authenticated_user_root
  end

  get '*path', to: redirect('/')
  # Do not add any routes below as they will be overwritten by the '*path' route.
end

app/models/job.rb
class Job < ActiveRecord::Base
  has_many :cvs
  mount_uploader :logo, CompanyLogoUploader

  def self.search(search_query)
    if search_query
      self.where("title LIKE ? OR description LIKE ?", "%#{search_query}%", "%#{search_query}%")
    else
      self.order(created_at: :desc)
    end
  end
end

app/controllers/admin/jobs_controller.rb
class Admin::JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

   def index
    @jobs = Job.search params[:search]

    @jobs = filter_by_category      @jobs
    @jobs = filter_by_created_date  @jobs
    @jobs = filter_by_deadline      @jobs
  end

  def show
    @job = Job.find params[:id]
  end

  def show
  end

  def new
    @job = Job.new
  end

  def edit
  end

  def create
    @job = Job.new job_params

    if @job.save
      redirect_to [:admin, @job], notice: 'Job was successfully created!'
    else
      render action: 'new'
    end
  end

  def update
    if @job.update job_params
      redirect_to [:admin, @job], notice: 'Job was successfully updated!'
    else
      render action: 'edit'
    end
  end

  def destroy
    notice = if @job.destroy
      'Job was successfully deleted.'
    else
      'An error occured while deleting the job!'
    end
    redirect_to admin_jobs_url, notice: notice
  end

  private

  def set_job
    @job = Job.find(params[:id])
  end

  def job_params
    params.require(:job).permit(:id, :title, :description, :logo, :deadline, :salary, :category)
  end

  def filter_by_category jobs
    return jobs if params[:category].nil? || params[:category] == "All categories"
    @current_category = params[:category]
    jobs.where category: params[:category]
  end

  def filter_by_created_date jobs
    return jobs unless params[:date].present?
    @current_date = params[:date]
    created_date_order = params[:date] == "Oldest" ? :asc : :desc
    jobs.reorder created_at: created_date_order
  end

  def filter_by_deadline jobs
    return jobs unless params[:deadline].present?
    @current_deadline = params[:deadline]
    if params[:deadline] == "Upcoming"
      jobs.reorder deadline: :asc
    elsif params[:deadline] == "Furthest"
      jobs.reorder deadline: :desc
    else
      jobs
    end
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def index
    @jobs = Job.search params[:search]

    @jobs = filter_by_category      @jobs
    @jobs = filter_by_created_date  @jobs
    @jobs = filter_by_deadline      @jobs
  end

  def show
    @job = Job.find params[:id]
  end

  private

  def filter_by_category jobs
    return jobs if params[:category].nil? || params[:category] == "All categories"
    @current_category = params[:category]
    jobs.where category: params[:category]
  end

  def filter_by_created_date jobs
    return jobs unless params[:date].present?
    @current_date = params[:date]
    created_date_order = params[:date] == "Oldest" ? :asc : :desc
    jobs.reorder created_at: created_date_order
  end

  def filter_by_deadline jobs
    return jobs unless params[:deadline].present?
    @current_deadline = params[:deadline]
    if params[:deadline] == "Upcoming"
      jobs.reorder deadline: :asc
    elsif params[:deadline] == "Furthest"
      jobs.reorder deadline: :desc
    else
      jobs
    end
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/admin/jobs/_form.html.haml
.formatted-form
  %h1 Job form
  %h2.sub-title Fill the fields below.
  = form_for [:admin, @job] do |f|
    = f.text_field :title, placeholder: 'Job title'
    = f.text_field :description, placeholder: 'Job description'
    = f.text_field :deadline, placeholder: 'Job deadline date'
    = f.number_field :salary, placeholder: 'Job salary'
    = f.text_field :category, placeholder: 'Job category'
    = f.label :logo, "Logo"
    = f.file_field :logo
    = f.submit
  .under-form-links
    = link_to '↫ BACK', admin_jobs_path, class: "link"

app/views/admin/jobs/edit.html.haml
= render 'bg'
= render 'form'
.under-form-links
  = link_to 'Back', admin_jobs_path

app/views/admin/jobs/index.html.haml
= render 'bg'

.centered-btn= link_to 'New Job', new_admin_job_path, class: "link"

.filter-box
  .search
    %p Search:
    = form_tag admin_jobs_path, method: 'GET' do
      = text_field_tag :search
      = submit_tag "Search", name: nil
  .category
    %p Filter by category:
    - if @current_category.blank?
      .link-btn.currently-selected= link_to "All categories", params.slice(:search, :deadline, :date).merge(category: "All categories")
    - else
      .link-btn= link_to "All categories", params.slice(:search, :deadline, :date).merge(category: "All categories")

    - if @current_category == 'Science'
      .link-btn.currently-selected= link_to "Science",        params.slice(:search, :deadline, :date).merge(category: "Science")
    - else
      .link-btn= link_to "Science",        params.slice(:search, :deadline, :date).merge(category: "Science")

    - if @current_category == 'Computing'
      .link-btn.currently-selected= link_to "Computing",      params.slice(:search, :deadline, :date).merge(category: "Computing")
    - else
      .link-btn= link_to "Computing",      params.slice(:search, :deadline, :date).merge(category: "Computing")

    - if @current_category == 'Engineering'
      .link-btn.currently-selected= link_to "Engineering",    params.slice(:search, :deadline, :date).merge(category: "Engineering")
    - else
      .link-btn= link_to "Engineering",    params.slice(:search, :deadline, :date).merge(category: "Engineering")

  .date-added
    %p Filter by added date:
    - if @current_date == 'Newest'
      .link-btn.currently-selected= link_to "Newest",         params.slice(:search, :category).merge(date: "Newest")
    - else
      .link-btn= link_to "Newest",         params.slice(:search, :category).merge(date: "Newest")
    - if @current_date == 'Oldest'
      .link-btn.currently-selected= link_to "Oldest",         params.slice(:search, :category).merge(date: "Oldest")
    - else
      .link-btn= link_to "Oldest",         params.slice(:search, :category).merge(date: "Oldest")
  .deadline
    %p Filter by deadline:
    - if @current_deadline == 'Upcoming'
      .link-btn.currently-selected= link_to "Upcoming",       params.slice(:search, :category).merge(deadline: "Upcoming")
    - else
      .link-btn= link_to "Upcoming",       params.slice(:search, :category).merge(deadline: "Upcoming")
    - if @current_deadline == 'Furthest'
      .link-btn.currently-selected= link_to "Furthest",       params.slice(:search, :category).merge(deadline: "Furthest")
    - else
      .link-btn= link_to "Furthest",       params.slice(:search, :category).merge(deadline: "Furthest")
  .clear-filters
    .link-btn= link_to "CLEAR FITLERS",  admin_jobs_path

- @jobs.each do |job|
  .job-details
    .job-title= job.title
    .job-content
      - if job.logo?
        = image_tag job.logo, class: "job-logo"
      .job-deadline
        %span.bold Deadline:
        = job.deadline
      .job-salary
        %span.bold Salary:
        = "£#{job.salary}"
      .job-category
        %span.bold Category:
        = job.category
      .job-description
        = job.description
    .center.job-links
      = link_to 'Edit', edit_admin_job_path(job), class: "link"
      |
      = link_to 'Remove', [:admin, job], method: :delete, data: { confirm: 'Are you sure?' }, class: "link"

app/views/admin/jobs/new.html.haml
= render 'bg'
= render 'form'

app/views/admin/jobs/show.html.haml
= render 'bg'

.job-details
  .job-title= @job.title
  .job-content
    - if @job.logo?
      = image_tag @job.logo, class: "job-logo"
    .job-deadline
      %span.bold Deadline:
      = @job.deadline
    .job-salary
      %span.bold Salary:
      = "£#{@job.salary}"
    .job-category
      %span.bold Category:
      = @job.category
    .job-description
      = @job.description
  .center
    = link_to 'Edit', edit_admin_job_path(@job), class: "link"
    |
    = link_to 'Remove', [:admin, @job], method: :delete, data: { confirm: 'Are you sure?' }, class: "link"

.centered-btn= link_to 'Back to jobs page', admin_jobs_path, class: "link"