config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  devise_for :staff_members

  unauthenticated do
    root to: 'pages#main'
  end

  namespace :admin do
    authenticate :staff_member do
      resources :cvs do
        resources :feedbacks
      end
      resources :feedbacks
      resources :jobs
      get '/stats', to: 'pages#stats'
      root 'jobs#index', as: :authenticated_admin_root
    end
  end

  authenticate :user do
    resources :jobs, only: [:index, :show] do
      resources :cvs
    end
    resources :cvs do
      resources :feedbacks, only: [:show] do
        post :accept, :reject
      end
      post :ready
    end
    get '/contact', to: 'pages#contact'
    root 'jobs#index', as: :authenticated_user_root
  end

  get '*path', to: redirect('/')
  # Do not add any routes below as they will be overwritten by the '*path' route.
end

app/models/cv.rb
class Cv < ActiveRecord::Base
  belongs_to :user
  belongs_to :job
  has_many :feedbacks
  has_many :custom_fields, dependent: :destroy
  accepts_nested_attributes_for :custom_fields, allow_destroy: true

  state_machine :status, initial: :pending do
    event :accept do
      transition :pending => :accepted
    end

    event :reject do
      transition :pending => :rejected
    end

    event :request_feedback do
      transition [:rejected, :accepted] => :pending
    end

    event :ready do
      transition :accepted => :ready
    end
  end
end

app/controllers/admin/cvs_controller.rb
class Admin::CvsController < ApplicationController
  def index
    @cvs = Cv.where(status: "pending")
  end
end

app/controllers/cvs_controller.rb
class CvsController < ApplicationController
  before_action :set_cv, only: [:show, :edit, :update, :destroy]

  def index
    if params[:job_id].present?
      @cvs = Job.find(params[:job_id]).cvs
    else
      @cvs = Cv.all
    end
  end

  def show
    if params[:job_id].present?
      @cv = Cv.where(job_id: params[:job_id], id: params[:id]).first
    end
  end

  def new
    @cv = Cv.new
    @cv.custom_fields.build
    @job = Job.find(params[:job_id]) if params[:job_id].present?
  end

  def edit
    @job = @cv.job
  end

  def create
    if params[:job_id].present?
      @job = Job.find(params[:job_id])

      @cv = @job.cvs.new(cv_params)
      @cv.user_id = current_user.id

      if @cv.save
        redirect_to [@job, @cv], notice: 'CV was successfully created!'
      else
        render action: 'new'
      end
    else
      @cv = @job.cvs.new(cv_params)
      @cv.user_id = current_user.id

      if @cv.save
        redirect_to @cv, notice: 'CV was successfully created!'
      else
        render action: 'new'
      end
    end
  end

  def update
    @cv.request_feedback unless @cv.pending?

    if @cv.update(cv_params)
      redirect_to @cv, notice: 'CV was successfully updated!'
    else
      render action: 'edit'
    end
  end

  def destroy
    notice = if @cv.destroy
      'CV was successfully deleted.'
    else
      'An error occured while deleting the CV!'
    end
    redirect_to cvs_url, notice: notice
  end

  def ready
    Cv.find(params[:cv_id]).ready
    redirect_to cvs_path
  end

  private

  def set_cv
    @cv = Cv.find(params[:id])
  end

  def cv_params
    params.require(:cv).permit(:id, :name, :address, :email, :phone_number, :personal_profile, :education, :technical_skills, :project_work,
      :professional_experience, :interests_and_achievements, :references, :job_id, :user_id, :created_at, custom_fields_attributes: [:id, :name, :content, :_destroy])
  end
end

app/helpers/cvs_helper.rb
module CvsHelper
end

app/views/cvs/_bg.html.haml
.bg-image.cvs-bg

app/views/cvs/_form.html.haml
%body
  %p.guidelines= link_to 'Need help? View our guidelines!', 'https://studyspace.kingston.ac.uk/bbcswebdav/orgs/SEC/Placements/2014-15/guides/CV%20Guide%202014.pdf', target: '_blank'
.formatted-form.cv-form
  %h1= "CV for #{@job.title}"
  %h2.sub-title Fill the fields below.
  = form_for [@job, @cv] do |f|
    .field
      = f.label :name, 'Your full name'
      = f.text_field :name, placeholder: 'Your full name', value: current_user.full_name
    .field
      = f.label :address, 'Address'
      = f.text_field :address, placeholder: 'Address', value: current_user.address
    .field
      = f.label :email, 'Email'
      = f.email_field :email, placeholder: 'Email', value: current_user.email
    .field
      = f.label :phone_number, 'Phone number'
      = f.phone_field :phone_number, placeholder: 'Phone number', value: current_user.phone_number
    .field
      = f.label :personal_profile, 'Personal profile'
      = f.text_area :personal_profile, placeholder: 'Personal profile', value: current_user.personal_profile
    .field
      = f.label :education, 'Education'
      = f.text_area :education, placeholder: 'Education', value: current_user.education
    .field
      = f.label :technical_skills, 'Technical skills'
      = f.text_area :technical_skills, placeholder: 'Technical skills', value: current_user.technical_skills
    .field
      = f.label :project_work, 'Project work'
      = f.text_area :project_work, placeholder: 'Project work', value: current_user.project_work
    .field
      = f.label :professional_experience, 'Professional experience'
      = f.text_area :professional_experience, placeholder: 'Professional experience', value: current_user.professional_experience
    .field
      = f.label :interests_and_achievements, 'Interests and achievements'
      = f.text_area :interests_and_achievements, placeholder: 'Interests and achievements', value: current_user.interests_and_achievements
    .field
      = f.label :references, 'References'
      = f.text_area :references, placeholder: 'References', value: current_user.references


    = f.nested_fields_for :custom_fields do |ff|
      .custom-field
        = ff.remove_nested_fields_link
        .field
          = ff.label :name, "Custom CV field name"
          = ff.text_field :name, placeholder: 'Custom CV field name'
        .field
          = ff.label :content, "Custom field content"
          = ff.text_area :content, placeholder: 'Custom field content'

    .add-custom-field
      = f.add_nested_fields_link :custom_fields, "Add custom field", class: "link add-custom-field"

    = f.submit
  .under-form-links
    = link_to '↫ BACK', cvs_path, class: "link"

app/views/cvs/edit.html.haml
= render 'bg'
= render 'form'

app/views/cvs/feedback_preview.html.haml
.feedback
  .feedback-info
    %table
      %tr
        %td Staff member:
        %td Michael Scofield
      %tr
        %td Created for:
        %td Job spec title
      %tr
        %td Created date:
        %td 19/01/2015 14:10
      %tr
        %td Feedback status:
        %td{:class => "feedback-status #{@feedback_status}"}= @feedback_status
    .buttons
      %button Edit CV
      %button Send new CV
.feedback-cv-preview CV PREVIEW

app/views/cvs/index.html.haml
= render 'bg'

/ .centered-btn= link_to "Create new CV", new_cv_path, class: 'link'

.preview-boxes
  - @cvs.each_with_index do |cv, index|
    .preview-box
      .header= "CV ##{index + 1}"
      %table
        - if cv.job.present?
          %tr
            %td Created for:
            %td= link_to cv.job.title, job_path(cv.job)
        %tr
          %td Created date:
          %td= cv.created_at.strftime("%H:%m %d.%m.%Y")
        %tr
          %td Status:
          - if cv.pending?
            %td.status.status-pending
              pending
          - elsif cv.feedbacks.last.present?
            %td.status{class: "status-#{cv.status}"}
              - if cv.ready?
                SENT!
              - elsif cv.feedbacks.last.accepted?
                ready to send
              - elsif cv.feedbacks.last.rejected?
                needs improvement
              - else
                pending
      .links
        - if cv.pending?
          = link_to "Show CV", cv_path(cv), class: "link"
        - else
          = link_to "Show CV and Feedback", [cv, cv.feedbacks.last], class: "link"
        |
        = link_to "Edit CV", edit_cv_path(cv), class: "link"
        |
        = link_to "Remove CV", cv_path(cv), data: { confirm: "Are you sure?" }, method: :delete, class: "link"
        - if cv.accepted?
          |
          = link_to "Apply for job", cv_ready_path(cv), method: :post, class: "link bold"

app/views/cvs/show.html.haml
= render 'bg'
.cv-template
  .cv-part
    .personal-details
      %p= @cv.name
      %p= @cv.address
      %p= "#{@cv.email}, #{@cv.phone_number}"

  .cv-part
    .header Personal Profile
    %p= @cv.personal_profile

  .cv-part
    .header Education
    %p= @cv.education

  .cv-part
    .header Technical Skills
    %p= @cv.technical_skills

  .cv-part
    .header Project Work
    %p= @cv.project_work

  .cv-part
    .header Professional Experience
    %p= @cv.professional_experience

  .cv-part
    .header Interests and Achievements
    %p= @cv.interests_and_achievements

  .cv-part
    .header References
    %p= @cv.references

  - @cv.custom_fields.each do |cf|
    .cv-part
      .header= cf.name
      %p= cf.content

  .under-form-links
    = link_to 'Edit', edit_cv_path(@cv), class: "link"
    |
    = link_to 'Back', cvs_path, class: "link"