config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  devise_for :staff_members

  unauthenticated do
    root to: 'pages#main'
  end

  namespace :admin do
    authenticate :staff_member do
      resources :cvs do
        resources :feedbacks
      end
      resources :feedbacks
      resources :jobs
      get '/stats', to: 'pages#stats'
      root 'jobs#index', as: :authenticated_admin_root
    end
  end

  authenticate :user do
    resources :jobs, only: [:index, :show] do
      resources :cvs
    end
    resources :cvs do
      resources :feedbacks, only: [:show] do
        post :accept, :reject
      end
      post :ready
    end
    get '/contact', to: 'pages#contact'
    root 'jobs#index', as: :authenticated_user_root
  end

  get '*path', to: redirect('/')
  # Do not add any routes below as they will be overwritten by the '*path' route.
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title CvSystem
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    %header
      - if user_signed_in?
        = link_to "SEC Placements", jobs_path, class: "logo"
      - elsif staff_member_signed_in?
        = link_to "SEC Placements", admin_jobs_path, class: "logo"
      - else
        = link_to "SEC Placements", root_path, class: "logo"

      %nav
        %ul
          - if user_signed_in?
            %li.greeting
              %p
                Logged in as:
                - if current_user.first_name.blank?
                  .bold= " #{current_user.email}"
                - else
                  .bold= " #{current_user.first_name} #{current_user.last_name}"
            %li= link_to "Jobs", jobs_path
            %li= link_to "My CVs", cvs_path
            %li= link_to "My account", edit_user_registration_path
            %li= link_to "Contact us", contact_path
            %li= link_to "Log out", destroy_user_session_path, method: :delete
          - elsif staff_member_signed_in?
            %li.greeting
              %p
                Logged in as:
                .bold= " #{ current_staff_member.first_name} #{current_staff_member.last_name}"
            %li= link_to "Jobs", admin_jobs_path
            %li.bold= link_to "Give feedback", admin_cvs_path
            %li= link_to "Given feedbacks", admin_feedbacks_path
            %li= link_to "My account", edit_staff_member_registration_path
            %li= link_to "Statistics", admin_stats_path
            %li= link_to "Log out", destroy_staff_member_session_path, method: :delete
          - else
            %li= link_to "Sign up", new_user_registration_path
            %li= link_to "Log in", new_user_session_path
    #container
      #notification
        - if notice
          %p.notice= notice
        - if alert
          %p.alert= alert
      = yield

app/views/layouts/homepage.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title CvSystem
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    #homepage
      = yield